fix(windows): force USE_CUDA/USE_ROCM definitions to ensure PyTorch guards are not bypassed (#303)
Should fix build errors like the one below because it is checking for[
`#if defined(_WIN32) && (defined(USE_CUDA) ||
defined(USE_ROCM))`](https://github.com/pytorch/pytorch/blob/main/torch/csrc/dynamo/compiled_autograd.h#L1110C1-L1110C64)
but `USE_CUDA` was not actually being set for various reasons.


```
C:/hostedtoolcache/windows/Python/3.11.9/x64/Lib/site-packages/torch/include\torch/csrc/dynamo/compiled_autograd.h(1134): error C2872: 'std': ambiguous symbol [D:\a\kernels-community\kernels-community\relu\build\_relu_5c0099e.vcxproj]
  C:/hostedtoolcache/windows/Python/3.11.9/x64/Lib/site-packages/torch/include\c10/util/strong_type.h(1583): note: could be 'std'
  C:/hostedtoolcache/windows/Python/3.11.9/x64/Lib/site-packages/torch/include\torch/csrc/dynamo/compiled_autograd.h(1134): note: or       'std'
  C:/hostedtoolcache/windows/Python/3.11.9/x64/Lib/site-packages/torch/include\torch/csrc/dynamo/compiled_autograd.h(1134): note: the template instantiation context (the oldest one first) is
  C:/hostedtoolcache/windows/Python/3.11.9/x64/Lib/site-packages/torch/include\torch/csrc/dynamo/compiled_autograd.h(1181): note: see reference to class template instantiation 'torch::dynamo::autograd::IValuePacker<__int64>' being compiled
  C:/hostedtoolcache/windows/Python/3.11.9/x64/Lib/site-packages/torch/include\torch/csrc/dynamo/compiled_autograd.h(1108): note: while compiling class template member function 'c10::TypePtr torch::dynamo::autograd::IValuePacker<__int64>::packed_type(void)'
  C:/hostedtoolcache/windows/Python/3.11.9/x64/Lib/site-packages/torch/include\torch/csrc/dynamo/compiled_autograd.h(1181): note: see the first reference to 'torch::dynamo::autograd::IValuePacker<__int64>::packed_type' in 'torch::dynamo::autograd::IValuePacker<unsigned __int64>::packed_type'
  ```